### ISSUE TITLE
Testcases testCompare and testModuleData are failing with python3

### ISSUE THREAD

**Issue by xambroz** [VirusTotal/yara-python#21]
Hello, 
when building the yara python3 module I run the tests.py and some of the tests are failing. Same tests do not fail for python2 (same environment, same directory just python3 instead of python2 resp. nosetests-3.4 instead of nosetests-2.7)

The testcase testModuleData seems to be always failing with python3.
The testcase testCompare seems to have some race condition and is sometimes failing with python3.

I am testing with version 9fd9fd290872e36360e5e3839c49e21a908bf128.

PYTHONPATH=/rpmbuild/BUILDROOT/python-yara-3.5.0-0.rc1.fc23.x86_64//usr/lib64/python3.4/site-packages/ nosetests-3.4 -v
testAnonymousStrings (tests.TestYara) ... ok
testArithmeticOperators (tests.TestYara) ... ok
testAt (tests.TestYara) ... ok
testBitwiseOperators (tests.TestYara) ... ok
testBooleanOperators (tests.TestYara) ... ok
testCallback (tests.TestYara) ... ok
testComments (tests.TestYara) ... ok
testCompare (tests.TestYara) ... FAIL
testComparisonOperators (tests.TestYara) ... ok
testCompileFile (tests.TestYara) ... ok
testCompileFiles (tests.TestYara) ... ok
testCount (tests.TestYara) ... ok
testEntrypoint (tests.TestYara) ... ok
testExternals (tests.TestYara) ... ok
testFilesize (tests.TestYara) ... ok
testFor (tests.TestYara) ... ok
testHexStrings (tests.TestYara) ... ok
testIn (tests.TestYara) ... ok
testIncludeFiles (tests.TestYara) ... ok
testIntegerFunctions (tests.TestYara) ... ok
testLength (tests.TestYara) ... ok
testModuleData (tests.TestYara) ... FAIL
testModules (tests.TestYara) ... ok
testOf (tests.TestYara) ... ok
testOffset (tests.TestYara) ... ok
testRE (tests.TestYara) ... ok
testStringIO (tests.TestYara) ... ok
testStrings (tests.TestYara) ... ok
testSyntax (tests.TestYara) ... ok
testWildcardStrings (tests.TestYara) ... ok
# 
## FAIL: testCompare (tests.TestYara)

Traceback (most recent call last):
  File "/rpmbuild/BUILD/yara-python-9fd9fd290872e36360e5e3839c49e21a908bf128/tests.py", line 840, in testCompare
    self.assertTrue(m[0] < m[1])
AssertionError: False is not true
# 
## FAIL: testModuleData (tests.TestYara)

Traceback (most recent call last):
  File "/rpmbuild/BUILD/yara-python-9fd9fd290872e36360e5e3839c49e21a908bf128/tests.py", line 930, in testModuleData
    self.assertTrue(data['constants']['foo'] == 'foo')
AssertionError: False is not true

Best regards
Michal Ambroz

**Comment by xambroz** [comment]
Hello,
The test case testModuleData actually fails on armv7hl platform as well even with python-2.7.

https://kojipkgs.fedoraproject.org//work/tasks/9958/15269958/build.log

Best regards
Michal Ambroz

**Comment by xambroz** [comment]
In general seems to be fixed in 3.9.0
