### ISSUE TITLE
Unable to build Sphnix documentation on macOS

### ISSUE THREAD

**Issue by seanthegeek** [VirusTotal/yara-python#234]
Building Sphinx documentation works fine in Debian but fails in macOS

```text
Running Sphinx v6.1.3

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/sean/dev/yaramail/venv/lib/python3.10/site-packages/sphinx/config.py", line 351, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/Users/sean/dev/yaramail/docs/source/conf.py", line 17, in <module>
    from yaramail import __version__
  File "/Users/sean/dev/yaramail/yaramail/__init__.py", line 9, in <module>
    import yara
ImportError: dlopen(/Users/sean/dev/yaramail/venv/lib/python3.10/site-packages/yara.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_EVP_MD_get_size'

make: *** [html] Error 2
```

**Comment by plusvic** [comment]
It looks like the OpenSSL is not being found. Which method did you use for installing `yara-python`?
