### ISSUE TITLE
A strange error was encountered after pip install yara-python

### ISSUE THREAD

**Issue by Make-Ye** [VirusTotal/yara-python#263]
Failed to import 'C:\Users\Name\AppData\Local\Programs\Python\Python311\DLLs\libyara.dll'
Traceback (most recent call last):
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\site-packages\yara\__init__.py", line 7, in <module>
    from yara.rules import compile
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\site-packages\yara\rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\site-packages\yara\libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\Name\AppData\Local\Programs\Python\Python311\DLLs\libyara.dll' (or one of its dependencies). Try using the full path with constructor syntax.

when I looked for the file, it turned out to be in this directory for me：
C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\site-packages\Users\Name\AppData\Local\Programs\Python\Python310\DLLs

**Comment by wxsBSD** [comment]
I think you installed the wrong one. You want to use yara-python.

**Comment by HydraDragonAntivirus** [comment]
I think you installed via `pip install yara`
