### ISSUE TITLE
yara match hangs on windows 10

### ISSUE THREAD

**Issue by ghost** [VirusTotal/yara-python#71]
import yara
import sys

rule = yara.compile(filepath=sys.argv[1])
m = rule.match(pid=int(sys.argv[2]))
print(m)

rule ExampleRule
{
    strings:
        $my_text_string = "AAAAAA"

    condition:
        $my_text_string 
}

C:\Users\User\Desktop>python y.py test.yar 7560
Traceback (most recent call last):
  File "y.py", line 6, in <module>
    m = rule.match(pid=int(sys.argv[2]))
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\yara\rules.py", line 354, in match
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\yara\rules.py", line 326, in match_proc
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\yara\rules.py", line 179, in match
    fnc(*args)
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\yara\libyara_wrapper.py", line 570, in yr_scan_proc
yara.libyara_wrapper.YaraMatchError: Not enough memory

C:\Users\User\Desktop>pip show yara-python
Name: yara-python
Version: 3.7.0
Summary: Python interface for YARA
Home-page: https://github.com/VirusTotal/yara-python
Author: Victor M. Alvarez
Author-email: plusvic@gmail.com;vmalvarez@virustotal.com
License: Apache 2.0
Location: c:\users\user\appdata\local\programs\python\python36\lib\site-packages
Requires:

C:\Users\User\Desktop>python --version
Python 3.6.3

**Comment by mephos** [comment]
The stacktrace shows that you are using `yara` (https://github.com/mjdorma/yara-ctypes/tree/master/yara) and not `yara-python` (per the explicit filenames **rules.py** and **libyara_wrapper.py**)

Try uninstalling `yara `and keeping only `yara-python` and then try again
